project:
  type: book
  output-dir: docs

book:
  title: "Transport Data Science"
  author: "Robin Lovelace"
  description: "A book on Transport Data Science."
  site-url: https://tdscience.github.io
  repo-url: https://github.com/tdscience/tdscience
  repo-branch: main
  repo-actions: [edit]
  page-footer:
    left: "Last updated: {{< var last-updated >}} UTC"
    right: "[![Build Status](https://github.com/tdscience/tdscience/actions/workflows/publish.yml/badge.svg)](https://github.com/tdscience/tdscience/actions/workflows/publish.yml)"
  
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true
    number-sections: true
