name: Deploy Book

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Generate Last Updated Variable
        run: |
          echo "last-updated: \"$(date +'%Y-%m-%d %H:%M')\"" > _variables.yml

      - name: Render Quarto Book
        run: |
          quarto render

      - name: Deploy to GitHub Pages Repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: tdscience/tdscience.github.io
          publish_branch: master
          publish_dir: ./docs
